import { Product, Artisan, Review, ProductCategory } from './types';

export const artisans: Artisan[] = [
  {
    id: 'artisan-1',
    name: 'Maria Rodriguez',
    avatar: 'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150&h=150&fit=crop&crop=face',
    bio: 'Master jewelry designer with 15 years of experience creating unique handcrafted pieces using traditional techniques.',
    rating: 4.9,
    reviewCount: 127,
    specialties: ['jewelry', 'necklaces'],
    experience: 15,
    location: 'Mexico City, Mexico',
  },
  {
    id: 'artisan-2',
    name: 'Ahmed Hassan',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face',
    bio: 'Traditional potter specializing in hand-thrown ceramics and decorative pottery with intricate designs.',
    rating: 4.8,
    reviewCount: 89,
    specialties: ['pottery', 'ceramics'],
    experience: 12,
    location: 'Cairo, Egypt',
  },
  {
    id: 'artisan-3',
    name: 'Yuki Tanaka',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face',
    bio: 'Textile artist creating handwoven scarves and traditional Japanese-inspired fabric designs.',
    rating: 4.7,
    reviewCount: 156,
    specialties: ['textiles', 'scarves'],
    experience: 8,
    location: 'Kyoto, Japan',
  },
];

export const products: Product[] = [
  {
    id: 'product-1',
    name: 'Handcrafted Silver Necklace',
    description: 'A stunning handcrafted silver necklace with intricate filigree work and natural gemstone pendant.',
    price: 450,
    category: 'jewelry',
    image: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce3b7?w=600&h=400&fit=crop',
    materials: ['Sterling silver', 'Natural gemstone', 'Handcrafted filigree'],
    dimensions: '18" chain length',
    isHandmade: true,
    isEcoFriendly: true,
    rating: 4.9,
    reviewCount: 23,
    artisan: artisans[0],
    available: true,
    customizations: [
      { id: 'custom-1', name: 'Custom Length', price: 50, description: 'Adjustable chain length' },
      { id: 'custom-2', name: 'Gemstone Choice', price: 75, description: 'Choose your preferred gemstone' },
    ],
  },
  {
    id: 'product-2',
    name: 'Hand-Thrown Ceramic Vase',
    description: 'Beautiful hand-thrown ceramic vase with traditional patterns and natural glaze finish.',
    price: 120,
    category: 'pottery',
    image: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=600&h=400&fit=crop',
    materials: ['Stoneware clay', 'Natural glaze', 'Hand-thrown'],
    dimensions: '12" height x 8" diameter',
    isHandmade: true,
    isEcoFriendly: true,
    rating: 4.8,
    reviewCount: 45,
    artisan: artisans[1],
    available: true,
    customizations: [
      { id: 'custom-3', name: 'Custom Size', price: 30, description: 'Adjustable dimensions' },
      { id: 'custom-4', name: 'Custom Glaze', price: 25, description: 'Choose your glaze color' },
    ],
  },
  {
    id: 'product-3',
    name: 'Handwoven Silk Scarf',
    description: 'Luxurious handwoven silk scarf with traditional Japanese patterns and natural dyes.',
    price: 85,
    category: 'textiles',
    image: 'https://images.unsplash.com/photo-1481391319762-47dff72954d9?w=600&h=400&fit=crop',
    materials: ['Pure silk', 'Natural dyes', 'Handwoven'],
    dimensions: '72" x 12"',
    isHandmade: true,
    isEcoFriendly: true,
    rating: 4.9,
    reviewCount: 67,
    artisan: artisans[2],
    available: true,
    customizations: [
      { id: 'custom-5', name: 'Custom Pattern', price: 20, description: 'Choose your pattern design' },
      { id: 'custom-6', name: 'Gift Wrapping', price: 10, description: 'Elegant gift packaging' },
    ],
  },
  {
    id: 'product-4',
    name: 'Handcrafted Leather Wallet',
    description: 'Premium handcrafted leather wallet with traditional stitching and natural vegetable-tanned leather.',
    price: 95,
    category: 'leather',
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&h=400&fit=crop',
    materials: ['Vegetable-tanned leather', 'Brass hardware', 'Hand-stitched'],
    dimensions: '4.5" x 3.5"',
    isHandmade: true,
    isEcoFriendly: true,
    rating: 4.7,
    reviewCount: 34,
    artisan: artisans[0],
    available: true,
    customizations: [
      { id: 'custom-7', name: 'Custom Embossing', price: 15, description: 'Personalized initials' },
      { id: 'custom-8', name: 'Leather Color', price: 25, description: 'Choose leather color' },
    ],
  },
  {
    id: 'product-5',
    name: 'Hand-Painted Ceramic Bowl',
    description: 'Artistic hand-painted ceramic bowl with traditional motifs and food-safe glaze.',
    price: 65,
    category: 'pottery',
    image: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=600&h=400&fit=crop',
    materials: ['Stoneware clay', 'Hand-painted', 'Food-safe glaze'],
    dimensions: '6" diameter x 3" height',
    isHandmade: true,
    isEcoFriendly: true,
    rating: 4.6,
    reviewCount: 28,
    artisan: artisans[1],
    available: true,
    customizations: [
      { id: 'custom-9', name: 'Custom Design', price: 20, description: 'Personalized painting' },
      { id: 'custom-10', name: 'Set of 4', price: 200, description: 'Complete set of bowls' },
    ],
  },
  {
    id: 'product-6',
    name: 'Handcrafted Wooden Cutting Board',
    description: 'Beautiful handcrafted wooden cutting board made from sustainable hardwood with natural oil finish.',
    price: 75,
    category: 'woodwork',
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&h=400&fit=crop',
    materials: ['Sustainable hardwood', 'Natural oil finish', 'Handcrafted'],
    dimensions: '18" x 12" x 1"',
    isHandmade: true,
    isEcoFriendly: true,
    rating: 4.8,
    reviewCount: 52,
    artisan: artisans[2],
    available: true,
    customizations: [
      { id: 'custom-11', name: 'Custom Size', price: 30, description: 'Adjustable dimensions' },
      { id: 'custom-12', name: 'Wood Type', price: 40, description: 'Choose wood species' },
    ],
  },
];

export const categories: ProductCategory[] = [
  { value: 'jewelry', label: 'Jewelry', icon: '💎' },
  { value: 'pottery', label: 'Pottery & Ceramics', icon: '🏺' },
  { value: 'textiles', label: 'Textiles & Scarves', icon: '🧣' },
  { value: 'leather', label: 'Leather Goods', icon: '👜' },
  { value: 'woodwork', label: 'Woodwork', icon: '🪵' },
  { value: 'glass', label: 'Glass Art', icon: '🪟' },
  { value: 'metalwork', label: 'Metalwork', icon: '⚒️' },
  { value: 'paper', label: 'Paper Crafts', icon: '📄' },
];

export const reviews: Review[] = [
  {
    id: 'review-1',
    productId: 'product-1',
    userId: 'user-1',
    userName: 'Sarah M.',
    rating: 5,
    comment: 'Absolutely beautiful craftsmanship! The necklace is even more stunning in person.',
    date: '2024-01-15',
  },
  {
    id: 'review-2',
    productId: 'product-1',
    userId: 'user-2',
    userName: 'Michael K.',
    rating: 4,
    comment: 'Great quality and fast shipping. The artisan clearly put a lot of care into this piece.',
    date: '2024-01-10',
  },
  {
    id: 'review-3',
    productId: 'product-2',
    userId: 'user-3',
    userName: 'Emma L.',
    rating: 5,
    comment: 'This vase is a work of art! Perfect addition to my home decor.',
    date: '2024-01-12',
  },
  {
    id: 'review-4',
    productId: 'product-3',
    userId: 'user-4',
    userName: 'David R.',
    rating: 4,
    comment: 'The silk scarf is incredibly soft and the pattern is beautiful. Highly recommend!',
    date: '2024-01-08',
  },
]; 