import { Product, Baker, Review, ProductCategory } from './types';

export const bakers: Baker[] = [
  {
    id: 'baker-1',
    name: 'Sarah Johnson',
    avatar: 'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150&h=150&fit=crop&crop=face',
    bio: 'Master pastry chef with 15 years of experience specializing in wedding cakes and French pastries.',
    rating: 4.9,
    reviewCount: 127,
    specialties: ['wedding-cakes', 'cupcakes'],
    experience: 15,
  },
  {
    id: 'baker-2',
    name: 'Michael Chen',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face',
    bio: 'Artisanal chocolate maker and cookie specialist with a passion for unique flavor combinations.',
    rating: 4.8,
    reviewCount: 89,
    specialties: ['chocolates', 'cookies'],
    experience: 12,
  },
  {
    id: 'baker-3',
    name: 'Emma Rodriguez',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face',
    bio: 'Vegan dessert expert creating delicious plant-based treats that everyone loves.',
    rating: 4.7,
    reviewCount: 156,
    specialties: ['vegan-desserts', 'pies'],
    experience: 8,
  },
];

export const products: Product[] = [
  {
    id: 'product-1',
    name: 'Royal Wedding Cake',
    description: 'A stunning three-tier wedding cake with vanilla bean buttercream and fresh flowers.',
    price: 450,
    category: 'wedding-cakes',
    image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&h=400&fit=crop',
    ingredients: ['Vanilla bean', 'Butter', 'Sugar', 'Flour', 'Eggs', 'Fresh flowers'],
    allergens: ['Gluten', 'Dairy', 'Eggs'],
    isVegan: false,
    isGlutenFree: false,
    rating: 4.9,
    reviewCount: 23,
    baker: bakers[0],
    available: true,
    customizations: [
      { id: 'custom-1', name: 'Extra Flowers', price: 50, description: 'Additional fresh flower decoration' },
      { id: 'custom-2', name: 'Gold Leaf', price: 75, description: 'Edible gold leaf accents' },
    ],
  },
  {
    id: 'product-2',
    name: 'Chocolate Cupcakes',
    description: 'Rich chocolate cupcakes with creamy vanilla frosting and sprinkles.',
    price: 24,
    category: 'cupcakes',
    image: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=600&h=400&fit=crop',
    ingredients: ['Dark chocolate', 'Cocoa powder', 'Butter', 'Sugar', 'Flour', 'Eggs', 'Vanilla'],
    allergens: ['Gluten', 'Dairy', 'Eggs'],
    isVegan: false,
    isGlutenFree: false,
    rating: 4.8,
    reviewCount: 45,
    baker: bakers[0],
    available: true,
    customizations: [
      { id: 'custom-3', name: 'Extra Frosting', price: 5, description: 'Double the frosting' },
      { id: 'custom-4', name: 'Custom Toppings', price: 8, description: 'Choose your toppings' },
    ],
  },
  {
    id: 'product-3',
    name: 'Artisan Chocolate Truffles',
    description: 'Handcrafted dark chocolate truffles with various fillings and coatings.',
    price: 35,
    category: 'chocolates',
    image: 'https://images.unsplash.com/photo-1481391319762-47dff72954d9?w=600&h=400&fit=crop',
    ingredients: ['Dark chocolate', 'Heavy cream', 'Butter', 'Vanilla', 'Cocoa powder'],
    allergens: ['Dairy'],
    isVegan: false,
    isGlutenFree: true,
    rating: 4.9,
    reviewCount: 67,
    baker: bakers[1],
    available: true,
    customizations: [
      { id: 'custom-5', name: 'Gift Box', price: 10, description: 'Elegant gift packaging' },
      { id: 'custom-6', name: 'Custom Flavors', price: 15, description: 'Choose your truffle flavors' },
    ],
  },
  {
    id: 'product-4',
    name: 'Vegan Chocolate Cake',
    description: 'Moist chocolate cake made with plant-based ingredients, topped with dairy-free frosting.',
    price: 45,
    category: 'vegan-desserts',
    image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&h=400&fit=crop',
    ingredients: ['Almond milk', 'Coconut oil', 'Cocoa powder', 'Flour', 'Sugar', 'Vanilla'],
    allergens: ['Gluten'],
    isVegan: true,
    isGlutenFree: false,
    rating: 4.7,
    reviewCount: 34,
    baker: bakers[2],
    available: true,
    customizations: [
      { id: 'custom-7', name: 'Gluten-Free', price: 8, description: 'Make it gluten-free' },
      { id: 'custom-8', name: 'Extra Frosting', price: 5, description: 'Additional dairy-free frosting' },
    ],
  },
  {
    id: 'product-5',
    name: 'Butter Cookies',
    description: 'Classic butter cookies with a delicate texture and rich flavor.',
    price: 18,
    category: 'cookies',
    image: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=600&h=400&fit=crop',
    ingredients: ['Butter', 'Sugar', 'Flour', 'Vanilla', 'Salt'],
    allergens: ['Gluten', 'Dairy'],
    isVegan: false,
    isGlutenFree: false,
    rating: 4.6,
    reviewCount: 28,
    baker: bakers[1],
    available: true,
    customizations: [
      { id: 'custom-9', name: 'Chocolate Dip', price: 6, description: 'Half-dipped in chocolate' },
      { id: 'custom-10', name: 'Custom Shapes', price: 4, description: 'Choose cookie shapes' },
    ],
  },
  {
    id: 'product-6',
    name: 'Apple Pie',
    description: 'Traditional apple pie with flaky crust and cinnamon-spiced filling.',
    price: 32,
    category: 'pies',
    image: 'https://images.unsplash.com/photo-1535920527002-bc64cfa7c7df?w=600&h=400&fit=crop',
    ingredients: ['Apples', 'Sugar', 'Cinnamon', 'Flour', 'Butter', 'Lemon juice'],
    allergens: ['Gluten', 'Dairy'],
    isVegan: false,
    isGlutenFree: false,
    rating: 4.8,
    reviewCount: 41,
    baker: bakers[2],
    available: true,
    customizations: [
      { id: 'custom-11', name: 'Extra Crust', price: 3, description: 'Double the crust' },
      { id: 'custom-12', name: 'Caramel Drizzle', price: 4, description: 'Add caramel sauce' },
    ],
  },
];

export const reviews: Review[] = [
  {
    id: 'review-1',
    productId: 'product-1',
    userId: 'user-1',
    userName: 'Jennifer Smith',
    rating: 5,
    comment: 'Absolutely stunning wedding cake! The flowers were beautiful and the taste was incredible. Highly recommend!',
    date: '2024-01-15',
  },
  {
    id: 'review-2',
    productId: 'product-2',
    userId: 'user-2',
    userName: 'Mike Johnson',
    rating: 4,
    comment: 'Great cupcakes! The chocolate flavor was rich and the frosting was perfect. Will order again.',
    date: '2024-01-10',
  },
  {
    id: 'review-3',
    productId: 'product-3',
    userId: 'user-3',
    userName: 'Lisa Chen',
    rating: 5,
    comment: 'These truffles are divine! The quality of chocolate is outstanding and the variety of flavors is amazing.',
    date: '2024-01-08',
  },
];

export const categories: { value: ProductCategory; label: string; icon: string }[] = [
  { value: 'wedding-cakes', label: 'Wedding Cakes', icon: '🎂' },
  { value: 'cupcakes', label: 'Cupcakes', icon: '🧁' },
  { value: 'cookies', label: 'Cookies', icon: '🍪' },
  { value: 'chocolates', label: 'Chocolates', icon: '🍫' },
  { value: 'vegan-desserts', label: 'Vegan Desserts', icon: '🌱' },
  { value: 'pies', label: 'Pies', icon: '🥧' },
]; 